### ISSUE TITLE
Personal

### ISSUE THREAD

**Issue by pkonneker** [byub/tv4cms#1]
I have an issue.

**Comment by pkonneker** [comment]
Can I tag @delence in this? I think i can.

A *bold* choice.

**Comment by pkonneker** [comment]
I think you can also reference other issues like DeathStarPlans#1

**Comment by trevorhreed** [comment]
byub/tv4cms#2

**Comment by trevorhreed** [comment]
#2

**Comment by trevorhreed** [comment]
Has this issue really been resolved? :)

**Comment by pkonneker** [comment]
Closed as won't fix. Problem is in underlying architecture.

😁
